### ISSUE TITLE
How does the "Plug.BasicAuth" example protect the LiveView socket using on_mount?

### ISSUE THREAD

**Issue by DriesCruyskens** [LivewareProblems/Orion#12]
The Orion docs reference the [LiveView docs on security](https://hexdocs.pm/phoenix_live_view/security-model.html#mounting-considerations) specifying to always perform authentication (and authorisation) in both the HTTP endpoints as well as a LiveView's `mount` callback. Later though, the docs provide an example that uses basic HTTP authentication to block access to the Orion dashboard. How does this example safeguard the LiveView socket from being accessed by unauthenticated/unauthorised requests (since there is no `on_mount` protection provided)? Does there exist a method to check for basic authentication inside a LiveView's mount callback?

Thank you for this awesome project and hopefully I don't take too much time out of your day to clarify this confusion.

**Comment by DianaOlympos** [comment]
Hello, for this answer, the reality is quite simple. It does not, but that does not matter because we do not need authorization. We use this the same way the LiveDashboard does it. If you think something is missing, I will offer you to take it up with the LiveDashboard people. Tbh I am not sure why they think it is enough, but I trust them more on this than I trust myself on this.
